alias ll='ls -lhag'

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export HDFS_NAMENODE_USER=root
export HDFS_DATANODE_USER=root
export HDFS_SECONDARYNAMENODE_USER=root
export YARN_RESOURCEMANAGER_USER=root
export YARN_NODEMANAGER_USER=root
export YARN_PROXYSERVER_USER=root
export HADOOP_HOME=/usr/local/hadoop
export HADOOP_YARN_HOME=${HADOOP_HOME}
export HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop
export HADOOP_LOG_DIR=${HADOOP_YARN_HOME}/logs
export HADOOP_IDENT_STRING=root
export HADOOP_MAPRED_IDENT_STRING=root
export HADOOP_MAPRED_HOME=${HADOOP_HOME}
export SPARK_HOME=/usr/local/spark
export CONDA_HOME=/usr/local/conda
export PYSPARK_MASTER=yarn
export PATH=${CONDA_HOME}/bin:${SPARK_HOME}/bin:${HADOOP_HOME}/bin:${PATH}